version: '2'

services:
  web:
    image: 'jmfirth/webpack'
    command: "sh -c 'node_modules/.bin/webpack --config webpack.prod.config.js -p'"
    working_dir: /src
    volumes:
      - ./:/src
      - ./static:/src/static
    environment:
      NODE_ENV: 'production'
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./static:/etc/nginx/html/
    ports:
      - 3000:80
  
  nlp:
    image: 'proycon/lamachine:latest'
    command: 'frog -S 12345'
    expose:
      - 12345
  
  flask:
    image: 'python:3'
    command: ["./wait-for.sh", "nlp:12345", "--", "./run.sh"]
    working_dir: /flask
    volumes:
      - ./flask:/flask
    environment:
     FLASK_APP: "app.py"
     SERVER_NAME: "0.0.0.0:5000"
    expose:
     - 5000