version: '2'

services:
  web:
    image: 'jmfirth/webpack'
    command: "sh -c 'yarn && NODE_ENV=development yarn web'"
    working_dir: /src
    volumes:
      - ./:/src
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      - NODE_ENV=development
  
  nlp:
    image: 'proycon/lamachine:latest'
    command: 'frog -S 12345'
    expose:
      - 12345
  
  flask:
    image: 'python:3'
    command: ["./wait-for.sh", "nlp:12345", "--", "./run.sh"]
    working_dir: /flask
    volumes:
      - ./flask:/flask
    environment:
     FLASK_APP: "app.py"
     FLASK_DEBUG: 1
     SERVER_NAME: "0.0.0.0:5000"
     PYTHONUSERBASE: /flask/vendor
    expose:
     - 5000
    links:
      - nlp